### ISSUE TITLE
User Experience Enhancement - Issue Report

### ISSUE THREAD

**Issue by iamyahia** [abdullahhussein1/TodoApp#3]
## Issue Title
**Title**: Enhance User Experience by Addressing UI/UX Concerns

## Introduction

I've noticed several user experience issues while navigating the Soft Steps Todo application. Addressing these concerns would greatly improve usability and overall satisfaction with the platform.

## Body

1. **Draggable Map in Home Page**: Currently, the map on the home page is draggable, which can lead to accidental movements. It's recommended to disable clicking to prevent unintentional map movements. You can refer to this [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/8fbcf5c9-e278-4b16-b848-ae040e41dc3e) for further details.

2. **Inactive Buttons**: The buttons throughout the application lack active states, which can cause confusion for users. Adding active states to buttons would provide visual feedback and enhance usability. Here are some examples to illustrate the issue:
a. [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/7e556100-6a71-4cea-a984-dd0a217ee723)
    b. [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/a7038cc9-a322-4ba0-a640-ab1942636de6)
c. [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/7ddf02b5-702a-4cc0-b667-e32126aede75)

4. **Task Duplication Issue**: Clicking multiple times on a single task results in duplication disappearing and unnecessary requests being sent. Utilizing an _abortController_ when fetching APIs can help mitigate this issue. Refer to this [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/2472639b-6390-4365-9e02-d204063dfbbc) for more information.

5. **Network Slowdown Impact**: Slowing down the network exposes issues such as unnecessary requests and slow asset loading. Implementing solutions such as optimizing assets with .SVG extension can improve performance. Here's an [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/1877a0d0-3c2c-47a1-b564-45bf32a5576c) demonstrating the problem.

6. **Header Color Contrast**: Important headers lack sufficient color contrast, impacting readability. Changing the color to white or a lighter shade would improve visibility. See this [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/8b82caf6-a55f-4883-bacf-88399d89027e) for reference.

7. **Dropdown and Priority Borders**: Dropdowns and priority selections exhibit inconsistent behavior with border appearance upon selection. This inconsistency can be confusing for users and should be addressed. Here's an [example](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/149edcaf-dc6e-491d-8661-9762d2843c49) showcasing the issue. Similar case happen in [priority dropdown](https://github.com/abdullahhussein1/soft-steps-todo-app/assets/90482598/0d8ae2ae-f229-43b0-9dba-348fb059a742)

**Comment by abdullahhussein1** [comment]
Great to see this detailed issue 💎 I appreciate it 🌸 جزاك الله خیرا
